### ISSUE TITLE
Rapid color cycling and breathing

### ISSUE THREAD

**Issue by tsibley** [keyboardio/Kaleidoscope-LEDEffect-Rainbow#9] opened 2018-06-05 22:17 UTC
At some point in the past couple days, after reflashing the firmware to adjust the key maps, this effect started cycling through the colors and breathing very quickly.  It's easily double or triple time compared to the previous speed. I tried rolling back a couple firmware versions—nothing systematic like a bisect—but it didn't help. Any thoughts or pointers?

**Comment by algernon** [comment] 2018-06-05 22:45
Are you using the master branch of everything?

Prior to 73d9997b5404c2565116e39df3606be54b9ca005, the speed of the animation depended on the speed of the main loop. We made the main loop considerably faster in the not too distant future... so if you upgraded Kaleidoscope, but not this plugin, that might explain the rapid speed.

**Comment by tsibley** [comment] 2018-06-06 00:19
I did a `make update-submodules` in my clone of `Arduino-Boards.git` (`~/Arduino/hardware/keyboardio/avr/`)… so I think the plugin is up-to-date?

**Comment by tsibley** [comment] 2018-06-06 00:20
(and that repo itself is up-to-date)

**Comment by tsibley** [comment] 2018-06-06 00:23
Hmm, but the submodule doesn't seem to have that commit applied.

**Comment by tsibley** [comment] 2018-06-06 00:29
This seems suspicious, but I don't use submodules enough to immediately know what happened:

![selection-006](https://user-images.githubusercontent.com/79913/41009442-030aa2d0-68e6-11e8-996f-ac7cd406a45e.png)

**Comment by tsibley** [comment] 2018-06-06 00:35
If I manually re-apply the patch and re-build and re-flash, it's back to being nice and calm and not rapid. :-) 

So somehow during a submodule update that commit got dropped from the Arduino-Boards repo.

**Comment by algernon** [comment] 2018-06-06 00:48
Thanks for digging into the issue and finding the root cause! I updated the `Arduino-Boards` repo, so the issue should be fixed now.

**Closed as completed by algernon** 2018-06-06 00:48 UTC

**Comment by tsibley** [comment] 2018-06-06 02:23
Great.  Thanks for the pointer for where to dig!
